version: '3'

services:
  web:
    build: .
    depends_on:
      - 'database'
    ports: 
      - '80:3001'

  database:
    image: mongo:latest
    ports:
    - "27017:27017"
  
  mongo-seed:
    build: ./database
    depends_on:
      - 'database'